name: Build VSIX

on:
  push:
    # Run on all commits to any branch
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed
  workflow_dispatch:
    # Manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.workflow_run.head_branch }}
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install vsce
      run: npm install -g @vscode/vsce
      
    - name: Package extension
      run: vsce package
      
    - name: Upload VSIX artifact
      uses: actions/upload-artifact@v4
      with:
        name: extension-package
        path: "*.vsix"
        if-no-files-found: error
        
    # Optional: Create GitHub release with the VSIX
    # - name: Create Release
    #   if: startsWith(github.ref, 'refs/tags/')
    #   uses: softprops/action-gh-release@v1
    #   with:
    #     files: "*.vsix"
